# Generated by Django 4.2.11 on 2025-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeroleassignment',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='online', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='type_description',
            field=models.CharField(max_length=1000),
        ),
    ]
